[versions]
# Versions
compileSdk = "33"
minSdk = "28"
targetSdk = "33"
appVersion = "1.0"
versionCode = "1"

# Kotlin
kotlin = "1.9.0"

# Build Tools and Plugins
gradleplugin = "8.1.2"

# AndroidX Libraries
coreKtx = "1.10.0"
appcompat = "1.6.1"
constraintlayout = "2.1.4"

# Google Libraries
material = "1.9.0"

# Test Libraries
junit = "4.13.2"
androidTestJunit = "1.1.5"
androidxTestEspresso = "3.5.1"

# Glide
glide = "4.16.0"

# hilt
hilt = "2.44"

# Lifecycle
lifecycle = "2.7.0"

# activity
activity = "1.8.2"

[libraries]
# AndroidX Libraries
coreKtx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }

# Google Libraries
material = { module = "com.google.android.material:material", version.ref = "material" }

# Test Libraries
androidTestJunit = { module = "androidx.test.ext:junit", version.ref = "androidTestJunit" }
androidxTestEspresso = { module = "androidx.test.espresso:espresso-core", version.ref = "androidxTestEspresso" }
junit = { module = "junit:junit", version.ref = "junit" }

# Glide
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }

# hilt
hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hiltKapt = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }

# lifecycle
viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }

# activity
activity = { module = "androidx.activity:activity-ktx", version.ref = "activity"}

[bundles]
androidDefault = ["coreKtx", "appcompat", "constraintlayout", "material"]
test = ["junit"]
androidUnitTest = ["androidTestJunit", "androidxTestEspresso"]

[plugins]
