[versions]
# Versions
compileSdk = "33"
minSdk = "28"
targetSdk = "33"
appVersion = "1.0"
versionCode = "1"

# AndroidX Libraries
coreKtx = "1.10.0"
appcompat = "1.6.1"
constraintlayout = "2.1.4"

# Google Libraries
material = "1.9.0"

# Test Libraries
junit = "4.13.2"
androidTestJunit = "1.1.5"
androidxTestEspresso = "3.5.1"


[libraries]
# AndroidX Libraries
coreKtx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }

# Google Libraries
material = { module = "com.google.android.material:material", version.ref = "material" }

# Test Libraries
androidTestJunit = { module = "androidx.test.ext:junit", version.ref = "androidTestJunit" }
androidxTestEspresso = { module = "androidx.test.espresso:espresso-core", version.ref = "androidxTestEspresso" }
junit = { module = "junit:junit", version.ref = "junit" }

[bundles]
androidDefault = ["coreKtx", "appcompat", "constraintlayout", "material"]
test = ["junit"]
androidUnitTest = ["androidTestJunit", "androidxTestEspresso"]

[plugins]
